services:
    - type: web
      name: draft-trade-analyzer-api
      env: node
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000
          - key: PG_HOST
            sync: false
          - key: PG_PORT
            sync: false
          - key: PG_DATABASE
            sync: false
          - key: PG_USER
            sync: false
          - key: PG_PASSWORD
            sync: false
      healthCheckPath: /
      autoDeploy: true
